In [1]:
import pandas as pd

In [2]:
# Load the Excel file from `data/landing` directory
file_path = '../../data/landing/income_14100DO0004_2011-23.xlsx'  
excel_data = pd.ExcelFile(file_path)

In [3]:
# `data/raw` directory: Convert Table 1 Sheet in Excel to CSV 
for sheet in excel_data.sheet_names:
    if sheet == 'Table 1':
        sheet_df = pd.read_excel(file_path, sheet_name=sheet)
        csv_file = f"../../data/raw/Income_SA2_{sheet}.csv"
        sheet_df.to_csv(csv_file, index=False)
        print(f"Saved '{sheet}' as {csv_file}")

Saved 'Table 1' as ../../data/raw/Income_SA2_Table 1.csv

# Table 1 Sheet (Victoria state by SA2)
### INCOME (INCLUDING GOVERNMENT ALLOWANCES), Australia, State and Territory, Statistical Areas Level 2-4, Greater Capital City Statistical Areas, 2011, 2016-2022

In [4]:
# `data/raw directory: Load the CSV file for Table 1, skipping the 6 lines of Header
table1_df = pd.read_csv('../../data/raw/Income_SA2_Table 1.csv', skiprows=6)

# display tables and features
table1_df.head()
print(f"Total entries: {len(table1_df)}")

Total entries: 23278

/var/folders/rz/jz9rr3bj0p54tkcg75wqd8l80000gn/T/ipykernel_57784/2077397483.py:2: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  table1_df = pd.read_csv('../../data/raw/Income_SA2_Table 1.csv', skiprows=6)

In [5]:
# select Victoria suburbs which has the 'Code' starting with '2', then remove GCCSA Code (Greater Capital City Statistical Areas) 
suburbs_victoria_df = table1_df[table1_df['Code'].astype(str).apply(lambda x: x.isnumeric() and x.startswith('2'))]

print(f'Total suburbs: {len(suburbs_victoria_df)}')
suburbs_victoria_df.head(50)

Total suburbs: 4848

,Code,Label,Year,Employee income earners (no.),Employee income earners - median age (years),Total employee income ($m),Median employee income ($),Mean employee income ($),Employee income as main source of income (%),Own unincorporated business income earners (no.),...,Income inadequately described or not stated (%),Median equivalised total household income (weekly) ($),$1-$499 per week (%).1,$500-$999 per week (%).1,$1000-$1999 per week (%).1,$2000-$2999 per week (%).1,$3000 or more per week (%).1,Nil income (%).1,Partial income stated (%),All incomes not stated (%)
16,2,Victoria,2011.0,-,-,-,-,-,-,-,...,-,751,-,-,-,-,-,-,-,-
17,2,Victoria,2016.0,3048110,38,174887.8,47469,57376,76.1,501879,...,8.7,864,21,29.1,28.9,6.4,2.7,2,7.5,2.5
18,2,Victoria,2017.0,3151400,38,184293.1,48219,58480,76.4,523202,...,-,-,-,-,-,-,-,-,-,-
19,2,Victoria,2018.0,3239361,38,196542,50019,60673,77,539640,...,-,-,-,-,-,-,-,-,-,-
20,2,Victoria,2019.0,3347084,38,208873.6,51688,62405,76.9,559515,...,-,-,-,-,-,-,-,-,-,-
21,2,Victoria,2020.0,3393012,38,219234.7,53323,64614,77.2,568765,...,-,-,-,-,-,-,-,-,-,-
22,2,Victoria,2021.0,-,-,-,-,-,-,-,...,6.8,1074,15.7,25.8,34.5,10.6,5.2,2,4.4,1.8
23,2,Victoria,2022.0,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
432,201,Ballarat,2011.0,-,-,-,-,-,-,-,...,-,616,-,-,-,-,-,-,-,-
433,201,Ballarat,2016.0,73277,41,3664.4,43732,50008,75.6,13365,...,9.6,708,27.8,32.8,23.6,3.2,1.3,1.3,6.8,3.1
434,201,Ballarat,2017.0,75660,41,3899.9,44933,51545,75.8,13748,...,-,-,-,-,-,-,-,-,-,-
435,201,Ballarat,2018.0,77210,41,4141.7,46987,53642,76.4,14022,...,-,-,-,-,-,-,-,-,-,-
436,201,Ballarat,2019.0,80080,41,4442.1,48655,55471,76.5,14154,...,-,-,-,-,-,-,-,-,-,-
437,201,Ballarat,2020.0,81858,40,4743,50507,57942,76.9,14316,...,-,-,-,-,-,-,-,-,-,-
438,201,Ballarat,2021.0,-,-,-,-,-,-,-,...,7.6,894,20.3,30.6,31.4,6.6,2.9,1.5,4.4,2.3
439,201,Ballarat,2022.0,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
440,202,Bendigo,2011.0,-,-,-,-,-,-,-,...,-,638,-,-,-,-,-,-,-,-
441,202,Bendigo,2016.0,71941,41,3622.4,44278,50352,74.1,13465,...,10.5,741,25.7,33.8,24.6,3.6,1.4,1.1,6.9,2.9
442,202,Bendigo,2017.0,74498,41,3849.9,45130,51678,74.5,13850,...,-,-,-,-,-,-,-,-,-,-
443,202,Bendigo,2018.0,75937,41,4095.5,47321,53933,75.2,13992,...,-,-,-,-,-,-,-,-,-,-
444,202,Bendigo,2019.0,78233,41,4368.8,49197,55843,75.2,14123,...,-,-,-,-,-,-,-,-,-,-
445,202,Bendigo,2020.0,79575,41,4656.2,51196,58513,75.7,14303,...,-,-,-,-,-,-,-,-,-,-
446,202,Bendigo,2021.0,-,-,-,-,-,-,-,...,8.1,923,18.9,30.6,32.7,6.9,2.8,1.4,4.5,2.1
447,202,Bendigo,2022.0,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
448,203,Geelong,2011.0,-,-,-,-,-,-,-,...,-,698,-,-,-,-,-,-,-,-
449,203,Geelong,2016.0,137303,40,7393.6,45300,53849,74.4,21487,...,9,804,22.9,31.8,27.8,4.6,1.6,1.2,7.2,2.8
450,203,Geelong,2017.0,143990,40,7982.8,46681,55440,75,22492,...,-,-,-,-,-,-,-,-,-,-
451,203,Geelong,2018.0,148434,40,8552.2,48686,57616,75.6,23399,...,-,-,-,-,-,-,-,-,-,-
452,203,Geelong,2019.0,154781,39,9233.4,50705,59655,75.6,24459,...,-,-,-,-,-,-,-,-,-,-
453,203,Geelong,2020.0,160103,39,9865.1,52285,61617,76,25646,...,-,-,-,-,-,-,-,-,-,-
454,203,Geelong,2021.0,-,-,-,-,-,-,-,...,6.9,1037,15.9,27.6,35.2,9.4,4,1.5,4.5,1.9
455,203,Geelong,2022.0,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
456,204,Hume,2011.0,-,-,-,-,-,-,-,...,-,631,-,-,-,-,-,-,-,-
457,204,Hume,2016.0,81500,42,3911.8,43005,47998,72.7,19896,...,10.7,730,26.1,33.4,24.4,2.9,1.2,1.2,7.3,3.5
458,204,Hume,2017.0,83901,42,4137.8,44217,49317,73.3,20167,...,-,-,-,-,-,-,-,-,-,-
459,204,Hume,2018.0,85535,42,4359,45739,50962,74.1,20290,...,-,-,-,-,-,-,-,-,-,-
460,204,Hume,2019.0,87748,42,4624.1,47552,52697,74.2,20253,...,-,-,-,-,-,-,-,-,-,-
461,204,Hume,2020.0,88586,42,4884.9,49560,55143,74.5,20421,...,-,-,-,-,-,-,-,-,-,-
462,204,Hume,2021.0,-,-,-,-,-,-,-,...,8.7,900,19.5,30.6,32.2,5.9,2.5,1.6,5,2.6
463,204,Hume,2022.0,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
464,205,Latrobe - Gippsland,2011.0,-,-,-,-,-,-,-,...,-,607,-,-,-,-,-,-,-,-
465,205,Latrobe - Gippsland,2016.0,121751,42,6286.3,42276,51633,71.8,29614,...,11.1,682,29.2,32.2,21.8,3.3,1.3,1.4,7.1,3.5
466,205,Latrobe - Gippsland,2017.0,124740,42,6479.5,42834,51944,72.2,30003,...,-,-,-,-,-,-,-,-,-,-
467,205,Latrobe - Gippsland,2018.0,126795,42,6794,44699,53582,73,29998,...,-,-,-,-,-,-,-,-,-,-
468,205,Latrobe - Gippsland,2019.0,131129,42,7229.3,46327,55131,73.3,30171,...,-,-,-,-,-,-,-,-,-,-
469,205,Latrobe - Gippsland,2020.0,133971,42,7629.5,48150,56949,73.7,30389,...,-,-,-,-,-,-,-,-,-,-
470,205,Latrobe - Gippsland,2021.0,-,-,-,-,-,-,-,...,9.3,824,22.2,31.6,28.4,5.7,2.5,2,4.8,2.9
471,205,Latrobe - Gippsland,2022.0,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
472,206,Melbourne - Inner,2011.0,-,-,-,-,-,-,-,...,-,1064,-,-,-,-,-,-,-,-
473,206,Melbourne - Inner,2016.0,366213,33,24581.9,52289,67125,79.2,53626,...,10.5,1190,14.9,18.8,32.5,12.8,7.4,4.5,7.3,1.7

In [6]:
# select entries where 'Label' contains 'Victoria'
label_victoria_df = table1_df[table1_df['Label'].str.contains('Victoria', na=False)]
print(f'Total entries containing Victoria: {len(label_victoria_df)}')
label_victoria_df.tail(10)

Total entries containing Victoria: 56

,Code,Label,Year,Employee income earners (no.),Employee income earners - median age (years),Total employee income ($m),Median employee income ($),Mean employee income ($),Employee income as main source of income (%),Own unincorporated business income earners (no.),...,Income inadequately described or not stated (%),Median equivalised total household income (weekly) ($),$1-$499 per week (%).1,$500-$999 per week (%).1,$1000-$1999 per week (%).1,$2000-$2999 per week (%).1,$3000 or more per week (%).1,Nil income (%).1,Partial income stated (%),All incomes not stated (%)
19798,506021123,Victoria Park - Lathlain - Burswood,2021.0,-,-,-,-,-,-,-,...,6.5,1314,11.1,20.7,35.5,14.7,9,1.9,6,1
19799,506021123,Victoria Park - Lathlain - Burswood,2022.0,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
22160,702051068,Victoria River,2011.0,-,-,-,-,-,-,-,...,-,535,-,-,-,-,-,-,-,-
22161,702051068,Victoria River,2016.0,260,37,9.8,29004,37565,93.1,-,...,27.7,527,37.1,15.1,20.3,4.5,1.7,3,11.9,6.4
22162,702051068,Victoria River,2017.0,295,35,11.6,29193,39258,95.2,18,...,-,-,-,-,-,-,-,-,-,-
22163,702051068,Victoria River,2018.0,338,35,12.2,24001,36181,95.9,15,...,-,-,-,-,-,-,-,-,-,-
22164,702051068,Victoria River,2019.0,357,35,13.2,26434,37104,95.7,23,...,-,-,-,-,-,-,-,-,-,-
22165,702051068,Victoria River,2020.0,386,35,15.3,28639,39614,95.7,23,...,-,-,-,-,-,-,-,-,-,-
22166,702051068,Victoria River,2021.0,-,-,-,-,-,-,-,...,14.2,442,50.1,13.3,16.9,6.3,1.5,0.6,7.6,3.8
22167,702051068,Victoria River,2022.0,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-

We notice that other Victorian locations were included like: 
* Royal Botanic Gardens, 
* Victoria River, 
* Victoria Park, 
* Victoria Point

In [7]:
# combine the two filtered datasets above
cleaned_victoria_df = pd.concat([suburbs_victoria_df, label_victoria_df]).drop_duplicates()
print(f'Total rows after filtered suburbs and : {len(cleaned_victoria_df)}')

Total rows after filtered suburbs and : 4888

In [8]:
print(f"Total columns: {len(cleaned_victoria_df.columns)}")
cleaned_victoria_df.columns

Total columns: 68

Index(['Code', 'Label', 'Year', 'Employee income earners (no.)',
       'Employee income earners - median age (years)',
       'Total employee income ($m)', 'Median employee income ($)',
       'Mean employee income ($)',
       'Employee income as main source of income (%)',
       'Own unincorporated business income earners (no.)',
       'Own unincorporated business income earners - median age (years)',
       'Total own unincorporated business income ($m)',
       'Median own unincorporated business income ($)',
       'Mean own unincorporated business income ($)',
       'Own unincorporated business income as main source of income (%)',
       'Investment income earners (no.)',
       'Investment income earners - median age (years)',
       'Total investment income ($m)', 'Median investment income ($)',
       'Mean investment income ($)',
       'Investment income as main source of income (%)',
       'Superannuation and annuity income earners (no.)',
       'Superannuation and annuity income earners - median age (years)',
       'Total superannuation and annuity income ($m)',
       'Median superannuation and annuity income ($)',
       'Mean superannuation and annuity income ($)',
       'Superannuation and annuity income as main source of income (%)',
       'Total income earners (excl. Government pensions and allowances) (no.)',
       'Total income earners (excl. Government pensions and allowances) - median age (years)',
       'Total income (excl. Government pensions and allowances) ($m)',
       'Median total income (excl. Government pensions and allowances) ($)',
       'Mean total income (excl. Government pensions and allowances) ($)',
       'Total income (excl. Government pensions and allowances) - p80/P20 ratio',
       'Total income (excl. Government pensions and allowances) - p80/P50 ratio',
       'Total income (excl. Government pensions and allowances) - p20/P50 ratio',
       'Total income (excl. Government pensions and allowances) - p10/P50 ratio',
       'Total income (excl. Government pensions and allowances) - gini coefficient',
       'Total income (excl. Government pensions and allowances) - income share of top 1% of earners',
       'Total income (excl. Government pensions and allowances) - income share of top 5% of earners',
       'Total income (excl. Government pensions and allowances) - income share of top 10% of earners',
       'Total income (excl. Government pensions and allowances) - lowest Quartile (%)',
       'Total income (excl. Government pensions and allowances) - second Quartile (%)',
       'Total income (excl. Government pensions and allowances) - third Quartile (%)',
       'Total income (excl. Government pensions and allowances) - highest Quartile (%)',
       'Persons who reported gross capital gains (no.)',
       'Total value of gross capital gains ($m)',
       'Median value of gross capital gains ($)',
       'Mean value of gross capital gains ($)',
       'Age pension - Department of Veterans' Affairs (no.)',
       'Service pension - Department of Veterans' Affairs (no.)',
       'Income support supplement - Department of Veterans' Affairs (no.)',
       '$1-$499 per week (%)', '$500-$999 per week (%)',
       '$1000-$1999 per week (%)', '$2000-$2999 per week (%)',
       '$3000 or more per week (%)', 'Nil income (%)', 'Negative income (%)',
       'Income inadequately described or not stated (%)',
       'Median equivalised total household income (weekly) ($)',
       '$1-$499 per week (%).1', '$500-$999 per week (%).1',
       '$1000-$1999 per week (%).1', '$2000-$2999 per week (%).1',
       '$3000 or more per week (%).1', 'Nil income (%).1',
       'Partial income stated (%)', 'All incomes not stated (%)'],
      dtype='object')

In [9]:
# filter relevant columns 
relevant_columns = [
    'Code', 'Label', 'Year', 
    'Employee income earners (no.)', 'Total employee income ($m)', 
    'Median employee income ($)', 'Mean employee income ($)', 
    'Own unincorporated business income earners (no.)', 
    'Total own unincorporated business income ($m)', 
    'Median own unincorporated business income ($)', 
    'Mean own unincorporated business income ($)', 
    'Investment income earners (no.)', 
    'Total investment income ($m)', 'Median investment income ($)', 
    'Mean investment income ($)', 
    'Total income (excl. Government pensions and allowances) ($m)', 
    'Median total income (excl. Government pensions and allowances) ($)', 
    'Mean total income (excl. Government pensions and allowances) ($)', 
    'Total income (excl. Government pensions and allowances) - gini coefficient', 
    'Total income (excl. Government pensions and allowances) - income share of top 1% of earners'
]

cleaned_victoria_df = cleaned_victoria_df[relevant_columns]

In [10]:
# drop missing values
cleaned_victoria_df = cleaned_victoria_df.dropna()
print(f'Total entries after dropping missing values: {len(cleaned_victoria_df)}')

Total entries after dropping missing values: 4888

In [11]:
# total locations in victoria 
len(cleaned_victoria_df)

4888

In [12]:
# final table
cleaned_victoria_df

,Code,Label,Year,Employee income earners (no.),Total employee income ($m),Median employee income ($),Mean employee income ($),Own unincorporated business income earners (no.),Total own unincorporated business income ($m),Median own unincorporated business income ($),Mean own unincorporated business income ($),Investment income earners (no.),Total investment income ($m),Median investment income ($),Mean investment income ($),Total income (excl. Government pensions and allowances) ($m),Median total income (excl. Government pensions and allowances) ($),Mean total income (excl. Government pensions and allowances) ($),Total income (excl. Government pensions and allowances) - gini coefficient,Total income (excl. Government pensions and allowances) - income share of top 1% of earners
16,2,Victoria,2011.0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
17,2,Victoria,2016.0,3048110,174887.8,47469,57376,501879,12011,11177,23932,2416209,23279.2,293,6854,202318.3,46984,60350,0.479,9.5
18,2,Victoria,2017.0,3151400,184293.1,48219,58480,523202,12933.2,11268,24719,2446441,23835.4,243,9743,213668.9,47709,61489,0.48,9.5
19,2,Victoria,2018.0,3239361,196542,50019,60673,539640,13763.8,11707,25505,2517491,25895.6,217,10286,228631.1,49266,63442,0.481,9.6
20,2,Victoria,2019.0,3347084,208873.6,51688,62405,559515,14371.5,11711,25686,2641282,27614.3,171,10455,242783.1,51027,65366,0.477,9.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22163,702051068,Victoria River,2018.0,338,12.2,24001,36181,15,0.3,21000,19417,88,0.1,33,1078,12,33656,44652,0.447,-
22164,702051068,Victoria River,2019.0,357,13.2,26434,37104,23,0.1,4021,5632,103,0.3,34,2994,13,34493,43083,0.454,-
22165,702051068,Victoria River,2020.0,386,15.3,28639,39614,23,-0.1,1378,-6478,114,0.1,7,1179,14.6,36161,44761,0.452,-
22166,702051068,Victoria River,2021.0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
22167,702051068,Victoria River,2022.0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-

In [13]:
# `/data/curated/` directory: Save to a CSV file
cleaned_victoria_df.to_csv('../../data/curated/Preprocessed_Income_Victoria_SA2.csv', index=False)