In [3]:
import pandas as pd

In [4]:
# Load the Excel file from `data/landing` directory
file_path = '../../data/landing/income_14100DO0004_2011-23.xlsx'  
excel_data = pd.ExcelFile(file_path)

In [6]:
# `data/raw` directory: Convert each sheet-tabs in Excel to CSV 
for sheet in excel_data.sheet_names:
    sheet_df = pd.read_excel(file_path, sheet_name=sheet)
    csv_file = f"../../data/raw/Income_{sheet}.csv"
    sheet_df.to_csv(csv_file, index=False)
    print(f"Saved {sheet} as {csv_file}")

Saved Contents as ../../data/raw/Income_Contents.csv
Saved Table 1 as ../../data/raw/Income_Table 1.csv
Saved Table 2 as ../../data/raw/Income_Table 2.csv

# Table 1 Sheet (Victoria state by SA2)
### INCOME (INCLUDING GOVERNMENT ALLOWANCES), Australia, State and Territory, Statistical Areas Level 2-4, Greater Capital City Statistical Areas, 2011, 2016-2022

In [7]:
# `data/raw directory: Load the CSV file for Table 1, skipping the 6 lines of Header
table1_df = pd.read_csv('../../data/raw/Income_Table 1.csv', skiprows=6)

# display tables and features
table1_df.head()

/var/folders/rz/jz9rr3bj0p54tkcg75wqd8l80000gn/T/ipykernel_54044/2338862357.py:2: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  table1_df = pd.read_csv('../../data/raw/Income_Table 1.csv', skiprows=6)

,Code,Label,Year,Employee income earners (no.),Employee income earners - median age (years),Total employee income ($m),Median employee income ($),Mean employee income ($),Employee income as main source of income (%),Own unincorporated business income earners (no.),...,Income inadequately described or not stated (%),Median equivalised total household income (weekly) ($),$1-$499 per week (%).1,$500-$999 per week (%).1,$1000-$1999 per week (%).1,$2000-$2999 per week (%).1,$3000 or more per week (%).1,Nil income (%).1,Partial income stated (%),All incomes not stated (%)
0,AUS,Australia,2011.0,-,-,-,-,-,-,-,...,-,763,-,-,-,-,-,-,-,-
1,AUS,Australia,2016.0,12171794,38,724934.7,48413,59559,76.7,1958072,...,9,877,21,28.5,29.1,6.8,2.8,1.6,7.8,2.4
2,AUS,Australia,2017.0,12442032,38,746501.2,49083,59998,76.9,2005237,...,-,-,-,-,-,-,-,-,-,-
3,AUS,Australia,2018.0,12685727,38,787316.7,50861,62063,77.7,2043758,...,-,-,-,-,-,-,-,-,-,-
4,AUS,Australia,2019.0,13007327,38,828414.6,52425,63688,77.4,2099436,...,-,-,-,-,-,-,-,-,-,-

In [8]:
# Filter the data for Victoria (replace 'Label' with the correct column name)
victoria_df = table1_df[table1_df['Label'].str.contains("Victoria", na=False)]
victoria_df.head(20)

,Code,Label,Year,Employee income earners (no.),Employee income earners - median age (years),Total employee income ($m),Median employee income ($),Mean employee income ($),Employee income as main source of income (%),Own unincorporated business income earners (no.),...,Income inadequately described or not stated (%),Median equivalised total household income (weekly) ($),$1-$499 per week (%).1,$500-$999 per week (%).1,$1000-$1999 per week (%).1,$2000-$2999 per week (%).1,$3000 or more per week (%).1,Nil income (%).1,Partial income stated (%),All incomes not stated (%)
16,2,Victoria,2011.0,-,-,-,-,-,-,-,...,-,751,-,-,-,-,-,-,-,-
17,2,Victoria,2016.0,3048110,38,174887.8,47469,57376,76.1,501879,...,8.7,864,21,29.1,28.9,6.4,2.7,2,7.5,2.5
18,2,Victoria,2017.0,3151400,38,184293.1,48219,58480,76.4,523202,...,-,-,-,-,-,-,-,-,-,-
19,2,Victoria,2018.0,3239361,38,196542,50019,60673,77,539640,...,-,-,-,-,-,-,-,-,-,-
20,2,Victoria,2019.0,3347084,38,208873.6,51688,62405,76.9,559515,...,-,-,-,-,-,-,-,-,-,-
21,2,Victoria,2020.0,3393012,38,219234.7,53323,64614,77.2,568765,...,-,-,-,-,-,-,-,-,-,-
22,2,Victoria,2021.0,-,-,-,-,-,-,-,...,6.8,1074,15.7,25.8,34.5,10.6,5.2,2,4.4,1.8
23,2,Victoria,2022.0,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
3168,50602,Belmont - Victoria Park,2011.0,-,-,-,-,-,-,-,...,-,893,-,-,-,-,-,-,-,-
3169,50602,Belmont - Victoria Park,2016.0,42939,34,2738.4,53040,63773,83.3,5568,...,11.7,983,19.1,24.5,31.4,9.2,3.4,2,8.5,1.9
3170,50602,Belmont - Victoria Park,2017.0,42637,34,2669.5,52829,62609,83.2,5674,...,-,-,-,-,-,-,-,-,-,-
3171,50602,Belmont - Victoria Park,2018.0,42318,35,2768.5,55519,65422,83.5,5893,...,-,-,-,-,-,-,-,-,-,-
3172,50602,Belmont - Victoria Park,2019.0,43028,35,2871.5,56360,66735,83.1,6088,...,-,-,-,-,-,-,-,-,-,-
3173,50602,Belmont - Victoria Park,2020.0,43957,36,3030,57779,68930,82.9,6454,...,-,-,-,-,-,-,-,-,-,-
3174,50602,Belmont - Victoria Park,2021.0,-,-,-,-,-,-,-,...,7.9,1186,14.5,21.5,35.6,12.7,6,1.9,6.5,1.3
3175,50602,Belmont - Victoria Park,2022.0,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
9888,206041507,Royal Botanic Gardens Victoria,2011.0,-,-,-,-,-,-,-,...,-,1125,-,-,-,-,-,-,-,-
9889,206041507,Royal Botanic Gardens Victoria,2016.0,-,-,-,-,-,-,-,...,-,3000,-,-,-,-,-,-,-,-
9890,206041507,Royal Botanic Gardens Victoria,2017.0,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
9891,206041507,Royal Botanic Gardens Victoria,2018.0,-,-,-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-

In [9]:
victoria_df.columns

Index(['Code', 'Label', 'Year', 'Employee income earners (no.)',
       'Employee income earners - median age (years)',
       'Total employee income ($m)', 'Median employee income ($)',
       'Mean employee income ($)',
       'Employee income as main source of income (%)',
       'Own unincorporated business income earners (no.)',
       'Own unincorporated business income earners - median age (years)',
       'Total own unincorporated business income ($m)',
       'Median own unincorporated business income ($)',
       'Mean own unincorporated business income ($)',
       'Own unincorporated business income as main source of income (%)',
       'Investment income earners (no.)',
       'Investment income earners - median age (years)',
       'Total investment income ($m)', 'Median investment income ($)',
       'Mean investment income ($)',
       'Investment income as main source of income (%)',
       'Superannuation and annuity income earners (no.)',
       'Superannuation and annuity income earners - median age (years)',
       'Total superannuation and annuity income ($m)',
       'Median superannuation and annuity income ($)',
       'Mean superannuation and annuity income ($)',
       'Superannuation and annuity income as main source of income (%)',
       'Total income earners (excl. Government pensions and allowances) (no.)',
       'Total income earners (excl. Government pensions and allowances) - median age (years)',
       'Total income (excl. Government pensions and allowances) ($m)',
       'Median total income (excl. Government pensions and allowances) ($)',
       'Mean total income (excl. Government pensions and allowances) ($)',
       'Total income (excl. Government pensions and allowances) - p80/P20 ratio',
       'Total income (excl. Government pensions and allowances) - p80/P50 ratio',
       'Total income (excl. Government pensions and allowances) - p20/P50 ratio',
       'Total income (excl. Government pensions and allowances) - p10/P50 ratio',
       'Total income (excl. Government pensions and allowances) - gini coefficient',
       'Total income (excl. Government pensions and allowances) - income share of top 1% of earners',
       'Total income (excl. Government pensions and allowances) - income share of top 5% of earners',
       'Total income (excl. Government pensions and allowances) - income share of top 10% of earners',
       'Total income (excl. Government pensions and allowances) - lowest Quartile (%)',
       'Total income (excl. Government pensions and allowances) - second Quartile (%)',
       'Total income (excl. Government pensions and allowances) - third Quartile (%)',
       'Total income (excl. Government pensions and allowances) - highest Quartile (%)',
       'Persons who reported gross capital gains (no.)',
       'Total value of gross capital gains ($m)',
       'Median value of gross capital gains ($)',
       'Mean value of gross capital gains ($)',
       'Age pension - Department of Veterans' Affairs (no.)',
       'Service pension - Department of Veterans' Affairs (no.)',
       'Income support supplement - Department of Veterans' Affairs (no.)',
       '$1-$499 per week (%)', '$500-$999 per week (%)',
       '$1000-$1999 per week (%)', '$2000-$2999 per week (%)',
       '$3000 or more per week (%)', 'Nil income (%)', 'Negative income (%)',
       'Income inadequately described or not stated (%)',
       'Median equivalised total household income (weekly) ($)',
       '$1-$499 per week (%).1', '$500-$999 per week (%).1',
       '$1000-$1999 per week (%).1', '$2000-$2999 per week (%).1',
       '$3000 or more per week (%).1', 'Nil income (%).1',
       'Partial income stated (%)', 'All incomes not stated (%)'],
      dtype='object')

In [10]:
relevant_columns = [
    'Code', 'Label', 'Year', 
    'Employee income earners (no.)', 'Total employee income ($m)', 
    'Median employee income ($)', 'Mean employee income ($)', 
    'Own unincorporated business income earners (no.)', 
    'Total own unincorporated business income ($m)', 
    'Median own unincorporated business income ($)', 
    'Mean own unincorporated business income ($)', 
    'Investment income earners (no.)', 
    'Total investment income ($m)', 'Median investment income ($)', 
    'Mean investment income ($)', 
    'Total income (excl. Government pensions and allowances) ($m)', 
    'Median total income (excl. Government pensions and allowances) ($)', 
    'Mean total income (excl. Government pensions and allowances) ($)', 
    'Total income (excl. Government pensions and allowances) - gini coefficient', 
    'Total income (excl. Government pensions and allowances) - income share of top 1% of earners'
]

In [11]:
# select relevant columns
victoria_df = victoria_df[relevant_columns]

In [12]:
victoria_df.head()

,Code,Label,Year,Employee income earners (no.),Total employee income ($m),Median employee income ($),Mean employee income ($),Own unincorporated business income earners (no.),Total own unincorporated business income ($m),Median own unincorporated business income ($),Mean own unincorporated business income ($),Investment income earners (no.),Total investment income ($m),Median investment income ($),Mean investment income ($),Total income (excl. Government pensions and allowances) ($m),Median total income (excl. Government pensions and allowances) ($),Mean total income (excl. Government pensions and allowances) ($),Total income (excl. Government pensions and allowances) - gini coefficient,Total income (excl. Government pensions and allowances) - income share of top 1% of earners
16,2,Victoria,2011.0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
17,2,Victoria,2016.0,3048110,174887.8,47469,57376,501879,12011,11177,23932,2416209,23279.2,293,6854,202318.3,46984,60350,0.479,9.5
18,2,Victoria,2017.0,3151400,184293.1,48219,58480,523202,12933.2,11268,24719,2446441,23835.4,243,9743,213668.9,47709,61489,0.48,9.5
19,2,Victoria,2018.0,3239361,196542,50019,60673,539640,13763.8,11707,25505,2517491,25895.6,217,10286,228631.1,49266,63442,0.481,9.6
20,2,Victoria,2019.0,3347084,208873.6,51688,62405,559515,14371.5,11711,25686,2641282,27614.3,171,10455,242783.1,51027,65366,0.477,9.5

In [13]:
# Drop rows with missing values, if necessary
victoria_df = victoria_df.dropna()

# Display cleaned data
victoria_df

,Code,Label,Year,Employee income earners (no.),Total employee income ($m),Median employee income ($),Mean employee income ($),Own unincorporated business income earners (no.),Total own unincorporated business income ($m),Median own unincorporated business income ($),Mean own unincorporated business income ($),Investment income earners (no.),Total investment income ($m),Median investment income ($),Mean investment income ($),Total income (excl. Government pensions and allowances) ($m),Median total income (excl. Government pensions and allowances) ($),Mean total income (excl. Government pensions and allowances) ($),Total income (excl. Government pensions and allowances) - gini coefficient,Total income (excl. Government pensions and allowances) - income share of top 1% of earners
16,2,Victoria,2011.0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
17,2,Victoria,2016.0,3048110,174887.8,47469,57376,501879,12011,11177,23932,2416209,23279.2,293,6854,202318.3,46984,60350,0.479,9.5
18,2,Victoria,2017.0,3151400,184293.1,48219,58480,523202,12933.2,11268,24719,2446441,23835.4,243,9743,213668.9,47709,61489,0.48,9.5
19,2,Victoria,2018.0,3239361,196542,50019,60673,539640,13763.8,11707,25505,2517491,25895.6,217,10286,228631.1,49266,63442,0.481,9.6
20,2,Victoria,2019.0,3347084,208873.6,51688,62405,559515,14371.5,11711,25686,2641282,27614.3,171,10455,242783.1,51027,65366,0.477,9.5
21,2,Victoria,2020.0,3393012,219234.7,53323,64614,568765,14483.6,11262,25465,2578237,26314.9,137,10207,251136.7,51996,66671,0.478,9.3
22,2,Victoria,2021.0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
23,2,Victoria,2022.0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
3168,50602,Belmont - Victoria Park,2011.0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
3169,50602,Belmont - Victoria Park,2016.0,42939,2738.4,53040,63773,5568,113.2,10526,20328,29891,136.9,131,4579,2837.5,52286,64195,0.449,5.9
3170,50602,Belmont - Victoria Park,2017.0,42637,2669.5,52829,62609,5674,108.3,9131,19081,29074,116.2,100,3997,2766.4,51400,62378,0.447,5.8
3171,50602,Belmont - Victoria Park,2018.0,42318,2768.5,55519,65422,5893,111.2,9247,18876,28879,118.2,93,4094,2881.8,53451,64412,0.445,5.9
3172,50602,Belmont - Victoria Park,2019.0,43028,2871.5,56360,66735,6088,122.6,9880,20137,29812,132.6,79,4449,3014.8,54770,66212,0.443,5.9
3173,50602,Belmont - Victoria Park,2020.0,43957,3030,57779,68930,6454,132.5,9624,20526,29645,146.3,57,4935,3187.7,55866,68398,0.447,6.5
3174,50602,Belmont - Victoria Park,2021.0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
3175,50602,Belmont - Victoria Park,2022.0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
9888,206041507,Royal Botanic Gardens Victoria,2011.0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
9889,206041507,Royal Botanic Gardens Victoria,2016.0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
9890,206041507,Royal Botanic Gardens Victoria,2017.0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
9891,206041507,Royal Botanic Gardens Victoria,2018.0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
9892,206041507,Royal Botanic Gardens Victoria,2019.0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
9893,206041507,Royal Botanic Gardens Victoria,2020.0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
9894,206041507,Royal Botanic Gardens Victoria,2021.0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
9895,206041507,Royal Botanic Gardens Victoria,2022.0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
13040,301021013,Victoria Point,2011.0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
13041,301021013,Victoria Point,2016.0,7448,420.5,48760,56457,908,20.5,13479,22605,5967,45.7,217,7652,476.1,46000,55725,0.446,6.5
13042,301021013,Victoria Point,2017.0,7433,425.1,49360,57186,918,21.3,11711,23252,5850,42.7,188,7302,478.2,46345,55884,0.443,6.3
13043,301021013,Victoria Point,2018.0,7557,443.1,50897,58635,927,21.5,11464,23219,6008,43.9,188,7303,508.7,48079,58047,0.448,7.1
13044,301021013,Victoria Point,2019.0,7502,448.8,52178,59830,940,21.6,10540,22929,6068,50.8,156,8368,514.5,48928,58702,0.446,6.4
13045,301021013,Victoria Point,2020.0,7477,450.5,52792,60254,924,20.5,12045,22213,5751,43.9,134,7630,506.8,49292,58198,0.44,5.4
13046,301021013,Victoria Point,2021.0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
13047,301021013,Victoria Point,2022.0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
19768,506021119,East Victoria Park - Carlisle,2011.0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
19769,506021119,East Victoria Park - Carlisle,2016.0,9972,659.2,54343,66103,1300,26.2,10540,20116,7126,27.1,141,3804,677.9,53329,65823,0.451,5.3
19770,506021119,East Victoria Park - Carlisle,2017.0,10115,652.7,53999,64523,1343,25.3,9505,18865,7033,25.6,105,3642,675.4,53000,64488,0.449,5.5
19771,506021119,East Victoria Park - Carlisle,2018.0,9854,670,56947,67990,1340,25.2,9620,18805,6922,27,107,3900,693.2,55022,66726,0.444,5.6
19772,506021119,East Victoria Park - Carlisle,2019.0,9974,689.9,57804,69170,1406,28.9,10786,20574,7204,30.5,94,4238,719.8,56185,68725,0.447,5.9
19773,506021119,East Victoria Park - Carlisle,2020.0,10147,724.4,58703,71391,1494,29.3,8843,19582,7098,32,78,4508,757.3,57391,71153,0.449,6.2
19774,506021119,East Victoria Park - Carlisle,2021.0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
19775,506021119,East Victoria Park - Carlisle,2022.0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
19792,506021123,Victoria Park - Lathlain - Burswood,2011.0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
19793,506021123,Victoria Park - Lathlain - Burswood,2016.0,9651,639.3,53275,66240,1249,27.9,9543,22304,7152,53.4,183,7472,683.9,53348,68471,0.473,6.7
19794,506021123,Victoria Park - Lathlain - Burswood,2017.0,9536,627.8,53222,65833,1284,28.1,7829,21847,7014,46.1,159,6568,668.5,52225,66540,0.473,6.5
19795,506021123,Victoria Park - Lathlain - Burswood,2018.0,9415,646.4,56409,68655,1332,30.4,9199,22812,6980,45.3,143,6487,694.4,54479,68662,0.47,6.3
19796,506021123,Victoria Park - Lathlain - Burswood,2019.0,9524,678.9,57582,71286,1375,30.5,8456,22211,7246,51,110,7036,733.4,55500,71174,0.473,7.1
19797,506021123,Victoria Park - Lathlain - Burswood,2020.0,9715,718.2,59067,73932,1508,38.2,9185,25338,7181,61.9,81,8626,784.4,56778,74496,0.484,9
19798,506021123,Victoria Park - Lathlain - Burswood,2021.0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
19799,506021123,Victoria Park - Lathlain - Burswood,2022.0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
22160,702051068,Victoria River,2011.0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
22161,702051068,Victoria River,2016.0,260,9.8,29004,37565,-,-,-,-,91,0.3,85,3052,9.7,40931,47136,0.413,-
22162,702051068,Victoria River,2017.0,295,11.6,29193,39258,18,0.3,17735,14913,106,0.4,42,3424,11.8,41025,47452,0.428,-
22163,702051068,Victoria River,2018.0,338,12.2,24001,36181,15,0.3,21000,19417,88,0.1,33,1078,12,33656,44652,0.447,-
22164,702051068,Victoria River,2019.0,357,13.2,26434,37104,23,0.1,4021,5632,103,0.3,34,2994,13,34493,43083,0.454,-
22165,702051068,Victoria River,2020.0,386,15.3,28639,39614,23,-0.1,1378,-6478,114,0.1,7,1179,14.6,36161,44761,0.452,-
22166,702051068,Victoria River,2021.0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
22167,702051068,Victoria River,2022.0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-

We notice that other Victorian locations were included like: 
* Royal Botanic Gardens, 
* Victoria River, 
* Victoria Park, 
* Victoria Point

In [14]:
# total locations in victoria 
len(victoria_df)

56

In [15]:
# `/data/curated/` directory: Save to a CSV file
victoria_df.to_csv('../../data/curated/preprocessed_Income_Victoria_State_SA2.csv', index=False)

# Table 2 Sheet (suburbs by LGA)
### INCOME (INCLUDING GOVERNMENT ALLOWANCES), Local Government Areas, 2011,2016-2022

In [16]:
# Load the Excel sheet for Table 2 and filter for Victoria
table2_df = pd.read_csv('../../data/raw/Income_Table 2.csv', skiprows=6)

# display tables and features
table2_df.head()

,Code,Label,Year,Employee income earners (no.),Employee income earners - median age (years),Total employee income ($m),Median employee income ($),Mean employee income ($),Employee income as main source of income (%),Own unincorporated business income earners (no.),...,Income inadequately described or not stated (%),Median equivalised total household income (weekly) ($),$1-$499 per week (%).1,$500-$999 per week (%).1,$1000-$1999 per week (%).1,$2000-$2999 per week (%).1,$3000 or more per week (%).1,Nil income (%).1,Partial income stated (%),All incomes not stated (%)
0,10050,Albury,2011.0,-,-,-,-,-,-,-,...,-,690,-,-,-,-,-,-,-,-
1,10050,Albury,2016.0,25821,39,1313.2,45382,50857,76.8,3985,...,10,776,24.5,33,26.6,3.9,1.5,1.1,6.5,2.8
2,10050,Albury,2017.0,25987,39,1346.7,46612,51820,77.2,3932,...,-,-,-,-,-,-,-,-,-,-
3,10050,Albury,2018.0,26652,39,1422.2,47998,53363,77.7,3937,...,-,-,-,-,-,-,-,-,-,-
4,10050,Albury,2019.0,27169,39,1493.6,49635,54976,78.4,3935,...,-,-,-,-,-,-,-,-,-,-

In [17]:
# Victoria suburbs has the 'Code' starting with '2' 
victoria_suburbs_df = table2_df[table2_df['Code'].astype(str).str.startswith('2')]

In [18]:
# select relevant columns
victoria_suburbs_df = victoria_suburbs_df[relevant_columns]
victoria_suburbs_df

,Code,Label,Year,Employee income earners (no.),Total employee income ($m),Median employee income ($),Mean employee income ($),Own unincorporated business income earners (no.),Total own unincorporated business income ($m),Median own unincorporated business income ($),Mean own unincorporated business income ($),Investment income earners (no.),Total investment income ($m),Median investment income ($),Mean investment income ($),Total income (excl. Government pensions and allowances) ($m),Median total income (excl. Government pensions and allowances) ($),Mean total income (excl. Government pensions and allowances) ($),Total income (excl. Government pensions and allowances) - gini coefficient,Total income (excl. Government pensions and allowances) - income share of top 1% of earners
1032,20110,Alpine,2011.0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
1033,20110,Alpine,2016.0,5984,258.2,36999,43155,1763,25,7796,14197,5428,38,497,7005,316.5,36669,44247,0.468,6.2
1034,20110,Alpine,2017.0,6047,268.1,38000,44344,1828,27.8,7194,15234,5367,39.6,472,7374,331.9,37350,45463,0.46,6
1035,20110,Alpine,2018.0,6267,286.1,39038,45646,1844,28.7,7939,15569,5543,46.4,436,8366,358.2,38607,47467,0.466,6.5
1036,20110,Alpine,2019.0,6264,298.1,41483,47593,1813,29.9,8997,16510,5595,46.2,353,8252,369.4,41286,49308,0.458,5.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1667,29399,Unincorporated Vic,2018.0,544,13.4,15933,24661,61,0.5,2981,8466,194,1.5,208,7533,-,-,-,-,-
1668,29399,Unincorporated Vic,2019.0,541,14.1,16809,26014,60,0.3,2964,5479,194,1.6,117,8267,13.7,20916,32581,0.48,-
1669,29399,Unincorporated Vic,2020.0,476,13.8,18260,29082,61,0.6,5593,9886,181,1.3,254,7060,12.8,25004,34854,0.432,-
1670,29399,Unincorporated Vic,2021.0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-
1671,29399,Unincorporated Vic,2022.0,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-,-

In [19]:
# '/data/curated/' directory: Save suburbs in Victoria to a CSV file
victoria_suburbs_df.to_csv('../../data/curated/preprocessed_Income_Suburb_Victoria_LGA.csv', index=False)